include: third_party/flutter/packages/flutter_tools/analysis_options.yaml

analyzer:
  exclude:
    - dotnet/
    - third_party/

# Allow importing Flutter tool's implementation files.
linter:
  rules:
    implementation_imports: false

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
