name: butter
description: .NET Bridge to Flutter
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_tools:
    path: third_party/flutter/packages/flutter_tools

dev_dependencies:
  flutter_test:
    sdk: flutter
